### ISSUE TITLE
Remove *R methods

### ISSUE THREAD

**Issue by gaelrenoux-datadome** [gaelrenoux/tranzactio#25] opened 2021-03-31 15:05 UTC
Hey, sorry to bump this, but I wanted to share something we use internally: 

```
  def transaction[E, A](tx: ZIO[Connection, E, A]): ZIO[Transactor, E, A] =
    Database.transactionOrDie(tx)

  def transaction[R, E, A](tx: ZIO[Connection with R, E, A])(implicit ev: R <:< Has[_]): ZIO[Transactor with R, E, A] =
    Database.transactionOrDieR(tx)
```

A very thin wrapper, delegating to tranzactio. I was able to create two overloads called `transaction`. Normally this doesn't work, since `[E, A]` and `[R, E, A]` have the same erasure, but turns out that sticking an implicit causes them to be different as far as Scala is concerned!

So I can have my cake and eat it too - a single `transaction` function (from the user's perspective) that handles either `Connection` or `Connection with R`.

Not sure if that ship had sailed (now that you've published v2.0), but maybe you could use this trick and remove the R overloads completely! :)

_Originally posted by @hmemcpy in https://github.com/gaelrenoux/tranzactio/issues/24#issuecomment-810220119_

**Comment by hmemcpy** [comment] 2021-03-31 15:13
Awesome! Thanks so much. Turns out this was an incomplete copy-paste, since the `R` also need to have a `<: Has[_]` constraint. So together with the implicit parameter this should be enough for Scala to treat those as distinct functions!

One more thing that happened, and I'm not sure why that is, was that calling `Database.transactionOrDieR(tx)` didn't work, and I got the strangest compilation error:

```
Transactor.scala:55:32: type mismatch;
 found   : zio.ZIO[io.github.gaelrenoux.tranzactio.doobie.Connection with R(in method transaction),E,A]
    (which expands to)  zio.ZIO[zio.Has[doobie.util.transactor.Transactor[zio.Task]] with R(in method transaction),E,A]
 required: zio.ZIO[io.github.gaelrenoux.tranzactio.doobie.Connection with R(in method transactionOrDieR),E,A]
    (which expands to)  zio.ZIO[zio.Has[doobie.util.transactor.Transactor[zio.Task]] with R(in method transactionOrDieR),E,A] [55:32]
```

(notice the `R(in method transaction)` and `R(in method transactionOrDieR)`) - for some reason it didn't know it was the same R! I was able to work around this by explicitly annotating it with: `Database.transactionOrDieR[R, E, A](tx)`
Intellij paints it red, for some reason, but at least it compiles... 🤷‍♂️

**Comment by gaelrenoux** [comment] 2021-06-12 12:48
OK, I finally took some time to play around this a bit, and it doesn't work (not easily, at least). The issue is, the transaction method have optional parameters (the `commitOnFailure` flag, and the `ErrorStrategies` implicit), so I hit the error: `multiple overloaded alternatives of method XXX define default arguments`.
Not sure what can be done. Having separate methods instead of optional arguments would complicate things a lot.

**Comment by hmemcpy** [comment] 2021-06-12 12:49
Yeah, unfortunately I had the same conclusion. Scala really doesn't like default arguments on overloaded methods. So without redesigning the API there's no easy solution. Oh well, it was a nice hack anyway :)

**Comment by gaelrenoux** [comment] 2021-06-12 12:51
Closing for now, might come back later if we completely redo the API at some point.

**Closed by gaelrenoux** 2021-06-12 12:51 UTC
